[build]
  base = "Frontend"
  publish = "build"
  command = "CI=false npm run build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200