services:
  - type: web
    name: edutack-backend
    env: node
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: edutack-db
          property: connectionString
      - key: EMAIL_USER
        value: libroflow8@gmail.com
      - key: EMAIL_PASS
        value: rkwvnraapvhezena